# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a2620ad6e262b516900338a3633c56b4737188dc

###

# фильтрация объявлений по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-12-23
Content-Type: application/json

###

# фильтрация объявлений по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация объявлений автору
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# пытаемся поменять объявление
PATCH {{baseUrl}}/advertisements/37/
Content-Type: application/json
Authorization: Token a2620ad6e262b516900338a3633c56b4737188dc

{
  "status": "CLOSED"
}

###

# пытаемся удалить объявление
DELETE {{baseUrl}}/advertisements/37/
Content-Type: application/json
Authorization: Token a2620ad6e262b516900338a3633c56b4737188dc

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
# Authorization: Token a2620ad6e262b516900338a3633c56b4737188dc

{
  "title": "test",
  "description": "test"
}