# Generated by Django 5.1.3 on 2024-11-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id_book_unique_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_book',
        ),
    ]
