name: Test-Action

on:
  push:
    branches: [ video ]

jobs:
  testing:
    runs-on: ubuntu-latest

    env:
      NAME: ${{ secrets.NAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}

    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.USER }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
          POSTGRES_DB: ${{ env.NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверка изменений
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Установка зависимостей
        run: |
          cd 3.2-crud/stocks_products
          pip install -r requirements.txt

      - name: Выполнение flake8
        run: |
          cd 3.2-crud/stocks_products
          flake8 . --exclude migrations --ignore E501,F401,E302,W293,W391,W292

      - name: Тесты
        run: |
          cd 3.2-crud/stocks_products
          python manage.py test
        env:
          NAME: ${{ env.NAME }}
          USER: ${{ env.USER }}
          PASSWORD: ${{ env.PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: testing

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Django_hw/3.2-crud/stocks_products
            git pull origin video
            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
