name: Test-Action

on:
  push:
    branches: [ video ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ secrets.NAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Проверка изменений
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Установка зависимостей
        run: pip install -r 3.2-crud/stocks_products/requirements.txt

      - name: Выполнение flake8
        run: flake8 stocks_products --exclude migrations --ignore E501,F401,E302,W293,W391,W292
